# Stop and start rabbitmq releated services on control node

- include: ../../common/service.yml
  vars:
    random_hosts: random_one_mq_host
    service_name: rabbitmq-server

- include: ../../common/service.yml
  vars:
    random_hosts: random_two_mq_hosts
    service_name: rabbitmq-server

- include: ../../common/service.yml
  vars:
    random_hosts: random_three_mq_hosts
    service_name: rabbitmq-server
