# This playbook will do specified service drill test cases, and if
# in manual mode, it will prompt to ask if you want to recover it.

- include: ../../common/next.yml
  vars:
    case_name: "CASE: Start to stress RabbitMQ"

- name: "Drill the case"
  hosts: localhost 
  gather_facts: true
  vars:
    execute: "{{ hostvars['localhost']['execute'] }}"
  tasks:
    - include_role:
        name: control
        tasks_from: stress_mq
      when:
        - execute == "y" or execute == true

- include: ../../common/ask.yml

- name: "Recover the fault"
  hosts: random_one_mq_host
  gather_facts: false
  vars:
    execute: "{{ hostvars['localhost']['execute'] }}"
    recovery: "{{ hostvars['localhost']['recovery'] }}"
  tasks:
    - include_role:
        name: control
        tasks_from: purge_queue
      when:
        - mode == "auto" or recovery == "y" or recovery == true
        - execute == "y" or execute == true
