---
language: python
python: "2.7"

install:
  - sudo pip install ansible

script:
  - ./drill.sh -p playbooks/drill_storage.yaml -i inventory/structure -t all --syntax-check

notifications:
  email: false
