manage_packages: true
mgmt_nic_name: "eth0"
tenant_nic_name: "eth0"
provider_nic_name: "eth0"
external_nic_name: "eth0"
storage_nic_name: "eth0"
storage_mgmt_nic_name: "eth0"

stress_mysql_time: 300
stress_mysql_host: localhost
sysbench_threads: 1000
sysbench_user: sysbench
sysbench_password: sysbench
sysbench_database: sysbench

physical_network_bridge: ovsbr3
physical_network_bridge_port: eth0

external_network_bridge: br-ex
external_network_bridge_port: eth0

rabbit_host: localhost
rabbit_username: guest
rabbit_password: guest

# Auth for OpenStack
os_auth_url: 'http://127.0.0.1:5000/v3'
os_project_domain_name: Default
os_user_domain_name: Default
os_admin_project: admin
os_admin_username: admin
os_admin_password: admin
os_gremlin_role: member
