# This playbook will do cpu stress load on Ceph Radosgw node

- name: "CASE: Storage - Stress ceph radosgw host CPU load to {{ cpu_stress_load }} for {{ cpu_stress_timeout }}"
  hosts: "{{ random_hosts }}"
  gather_facts: true
  tasks:
    - include_role:
        name: system
        tasks_from: cpu_load

- include: ../../utils/next.yml
