# This playbook will do radosgw kill drill test case, and if
# in manual mode, it will prompt to ask if you want to recover
# it.

- name: "CASE: Ceph radosgw down on {{ random_hosts }}"
  hosts: "{{ random_hosts }}"
  gather_facts: false
  tasks:
    - include_role:
        name: storage
        tasks_from: kill_rgw

- include: ../../common/ask.yml

- name: Recover fault
  hosts: "{{ random_hosts }}"
  gather_facts: true
  tasks:
    - block:
        - include_role:
            name: storage
            tasks_from: start_rgw
      vars:
        - recovery: "{{ hostvars['localhost']['recovery'] }}"
      when: mode == "auto" or recovery == "y" or recovery == "yes" 

- include: ../../common/next.yml
