# CPU
- include: cpu_load.yml
  vars:
    cpu_stress_load: "80%"
    cpu_stress_timeout: "5m"
  tags:
    - "{{ node_group }}-cpu"

- include: cpu_load.yml
  vars:
    cpu_stress_load: "90%"
    cpu_stress_timeout: "5m"
  tags:
    - "{{ node_group }}-cpu"

- include: cpu_load.yml
  vars:
    cpu_stress_load: "100%"
    cpu_stress_timeout: "5m"
  tags:
    - "{{ node_group }}-cpu"

# Memory
- include: mem_load.yml
  vars:
    mem_stress_load: "80%"
    mem_stress_timeout: "5m"
  tags:
    - "{{ node_group }}-mem"

- include: mem_load.yml
  vars:
    mem_stress_load: "90%"
    mem_stress_timeout: "5m"
  tags:
    - "{{ node_group }}-mem"

- include: mem_load.yml
  vars:
    mem_stress_load: "100%"
    mem_stress_timeout: "5m"
  tags:
    - "{{ node_group }}-mem"

# Disk(root disk)
- include: disk_load.yml
  vars:
    disk_stress_load: "80%"
    disk_stress_timeout: "5m"
  tags:
    - "{{ node_group }}-disk"

- include: disk_load.yml
  vars:
    disk_stress_load: "90%"
    disk_stress_timeout: "5m"
  tags:
    - "{{ node_group }}-disk"
