# This playbook will do cpu stress load on specified node

- include: ../common/next.yml
  vars:
    case_name: "CASE: Stress {{ node_group }} host CPU load to {{ cpu_stress_load }} for {{ cpu_stress_timeout }} on {{ random_hosts }}"

- name: "Drill the case"
  hosts: "{{ random_hosts }}"
  gather_facts: true
  vars:
    execute: "{{ hostvars['localhost']['execute'] }}"
  tasks:
    - include_role:
        name: system
        tasks_from: cpu_load
      when:
        - execute == "y" or execute == true
