# This playbook will do root file system stress load on specified node

- include: ../common/next.yml
  vars:
    case_name: "CASE: Stress {{ node_group }} host root file system load to {{ disk_stress_load }} for {{ disk_stress_timeout }} on {{ random_hosts }}"

- name: "Drill the case"
  hosts: "{{ random_hosts }}"
  gather_facts: true
  vars:
    execute: "{{ hostvars['localhost']['execute'] }}"
  tasks:
    - include_role:
        name: system
        tasks_from: disk_load
      when:
        - execute == "y" or execute == true
