# This playbook will do mem stress load on specified node

- name: "CASE: Stress {{ node_group }} host memory load to {{ mem_stress_load }} for {{ mem_stress_timeout }}"
  hosts: "{{ random_hosts }}"
  gather_facts: true
  tasks:
    - include_role:
        name: system
        tasks_from: mem_load

- include: ../common/next.yml
