# This playbook will do nic delay of specified nic on specified node

- name: "CASE: Set {{ node_group }} host {{ nic }} delay to {{ nic_delay_time }} for {{ nic_delay_timeout }}"
  hosts: "{{ random_hosts }}"
  gather_facts: false
  tasks:
    - include_role:
        name: system
        tasks_from: nic_delay

- include: ../utils/next.yml
