# This playbook will do nic loss of specified nic on specified node

- name: "CASE: Set {{ node_group }} host {{ nic }} loss to {{ nic_loss_percent }} for {{ nic_loss_timeout }}"
  hosts: "{{ random_hosts }}"
  gather_facts: false
  tasks:
    - include_role:
        name: system
        tasks_from: nic_loss

- include: ../utils/next.yml
