# This playbook will do nic delay of specified nic on specified node

- include: ../common/next.yml
  vars:
    case_name: "CASE: Set {{ node_group }} host {{ nic }} delay to {{ nic_delay_time }} for {{ nic_delay_timeout }} on {{ random_hosts }}"

- name: "Drill the case"
  hosts: "{{ random_hosts }}"
  gather_facts: false
  vars:
    execute: "{{ hostvars['localhost']['execute'] }}"
  tasks:
    - include_role:
        name: system
        tasks_from: nic_delay
      when:
        - execute == "y" or execute == true
