# This playbook will do nic loss of specified nic on specified node

- include: ../common/next.yml
  vars:
    case_name: "CASE: Set {{ node_group }} host {{ nic }} loss to {{ nic_loss_percent }} for {{ nic_loss_timeout }} on {{ random_hosts }}"

- name: "Drill the case"
  hosts: "{{ random_hosts }}"
  gather_facts: false
  vars:
    execute: "{{ hostvars['localhost']['execute'] }}"
  tasks:
    - include_role:
        name: system
        tasks_from: nic_loss
      when:
        - execute == "y" or execute == true
