# System Level
- include: ../system/base.yml
  vars:
    random_hosts: random_one_compute_host
    node_group: compute

- include: ../system/nic.yml
  vars:
    random_hosts: random_one_compute_host
    node_group: compute
    nic_type: tenant
    nic: "{{ tenant_nic_name }}"
  tags:
    - compute-tenant-nic

- include: ../system/nic.yml
  vars:
    random_hosts: random_one_compute_host
    node_group: compute
    nic_type: storage
    nic: "{{ storage_nic_name }}"
  tags:
    - compute-storage-nic
