- name: Ask if recover this fault when in manual mode
  hosts: localhost
  gather_facts: false
  vars:
    execute: "{{ hostvars['localhost']['execute'] }}"
  tasks:
    - set_fact:
        recovery: true
    - block:
        - pause:
            prompt: "Will recover this fault? (y|yes, n|no)"
          register: _recovery
        - set_fact:
            recovery: "{{ _recovery.user_input }}"
      when:
        - mode == "manual"
        - execute == "y" or execute == true
