# This playbook will do specified port drill test cases, and if
# in manual mode, it will prompt to ask if you want to recover it.

- include: next.yml
  vars:
    case_name: "CASE: Delete {{ ovs_port }} port from {{ ovs_bridge }} on {{ random_hosts }}"

- name: "Drill the case"
  hosts: "{{ random_hosts }}"
  gather_facts: false
  vars:
    execute: "{{ hostvars['localhost']['execute'] }}"
  tasks:
    - include_role:
        name: common
        tasks_from: port_del
      when:
        - execute == "y" or execute == true

- include: ask.yml

- name: "Recover the fault"
  hosts: "{{ random_hosts }}"
  gather_facts: false
  vars:
    execute: "{{ hostvars['localhost']['execute'] }}"
    recovery: "{{ hostvars['localhost']['recovery'] }}"
  tasks:
    - include_role:
        name: common
        tasks_from: port_add
      when:
        - mode == "auto" or recovery == "y" or recovery == true
        - execute == "y" or execute == true
