# Stop and start mariadb releated services on control node

- include: ../../common/service.yml
  vars:
    random_hosts: random_one_db_host
    service_name: mysql

- include: ../../common/service.yml
  vars:
    random_hosts: random_two_db_hosts
    service_name: mysql

- include: ../../common/service.yml
  vars:
    random_hosts: random_three_db_hosts
    service_name: mysql
