- include: ../../common/next.yml
  vars:
    case_name: "Stress MySQL Cluster using sysbench"

- name: "Drill the case"
  hosts: random_one_db_host
  gather_facts: false
  vars:
    execute: "{{ hostvars['localhost']['execute'] }}"
  tasks:
    - include_role:
        name: control
        tasks_from: stress_db
      when:
        - execute == "y" or execute == true
