## System Level
- include: ../system/base.yml
  vars:
    random_hosts: random_one_network_host
    node_group: network

- include: ../system/nic.yml
  vars:
    random_hosts: random_one_network_host
    node_group: network
    nic_type: tenant
    nic: "{{ tenant_nic_name }}"

- include: ../system/nic.yml
  vars:
    random_hosts: random_one_network_host
    node_group: network
    nic_type: external
    nic: "{{ external_nic_name }}"
