# Stop and start haproxy releated services on control node

- include: ../../common/service.yml
  vars:
    random_hosts: random_one_lb_host
    service_name: haproxy

- include: ../../common/service.yml
  vars:
    random_hosts: random_two_lb_hosts
    service_name: haproxy

- include: ../../common/service.yml
  vars:
    random_hosts: random_three_lb_hosts
    service_name: haproxy
