# Stop and start nova releated services on control node

# nova-api
- include: ../../common/service.yml
  vars:
    random_hosts: random_one_api_host
    service_name: openstack-nova-api

- include: ../../common/service.yml
  vars:
    random_hosts: random_two_api_hosts
    service_name: openstack-nova-api

- include: ../../common/service.yml
  vars:
    random_hosts: random_three_api_hosts
    service_name: openstack-nova-api

# nova-scheduler
- include: ../../common/service.yml
  vars:
    random_hosts: random_one_api_host
    service_name: openstack-nova-scheduler

- include: ../../common/service.yml
  vars:
    random_hosts: random_two_api_hosts
    service_name: openstack-nova-scheduler

- include: ../../common/service.yml
  vars:
    random_hosts: random_three_api_hosts
    service_name: openstack-nova-scheduler

# nova-conductor
- include: ../../common/service.yml
  vars:
    random_hosts: random_one_api_host
    service_name: openstack-nova-conductor

- include: ../../common/service.yml
  vars:
    random_hosts: random_two_api_hosts
    service_name: openstack-nova-conductor

- include: ../../common/service.yml
  vars:
    random_hosts: random_three_api_hosts
    service_name: openstack-nova-conductor
