- name: Ask if recover this fault when in manual mode
  hosts: localhost
  tasks:
    - set_fact:
        recovery: "no"
    - block:
        - pause:
            prompt: "Will recover this fault? (y|yes, n|no)"
          register: _recovery
        - set_fact:
            recovery: "{{ _recovery.user_input }}"
      when:
        - mode == "manual"
