- name: Preparing for mq node tests
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    shuffle_mq_hosts: "{{ groups['mq'] | shuffle }}"
    mq_group_num: "{{ groups['mq'] | length }}"
  tasks:
    - name: Random select one mq host
      add_host:
        groups: random_one_mq_host
        name: "{{ groups['mq'] | random }}"
      when:
        - mq_group_num | int >= 1

    - name: Random select two mq hosts
      add_host:
        groups: random_two_mq_hosts
        name: "{{ item }}"
      with_items:
        - "{{ shuffle_mq_hosts[:2] }}"
      when:
        - mq_group_num | int >= 2

    - name: Random select three mq hosts
      add_host:
        groups: random_three_mq_hosts
        name: "{{ item }}"
      with_items:
        - "{{ shuffle_mq_hosts[:3] }}"
      when:
        - mq_group_num | int >= 3
  tags:
    - mq-pre

- include: rabbitmq/service.yml
  tags:
    - service
    - mq
    - mq-service
    - control

# We mainly test the impact to the RabbitMQ cluster when
# there are network problems

# Nic delay(Management Network)
- include: ../system/nic_delay.yml
  vars:
    nic_delay_time: "300ms"
    nic_delay_timeout: "5m"
    nic: "{{ mgmt_nic_name }}"
    random_hosts: random_one_mq_host
  tags:
    - mq-mgmt-nic-delay
    - service
    - mq
    - mq-service
    - control

# Nic package loss(Management Network)
- include: ../system/nic_loss.yml
  vars:
    nic_loss_percent: "80%"
    nic_loss_timeout: "5m"
    nic: "{{ mgmt_nic_name }}"
    random_hosts: random_one_mq_host
  tags:
    - mq-mgmt-nic-loss
    - service
    - mq
    - mq-service
    - control

# Nic down(Management Network)
- include: ../system/nic_down.yml
  vars:
    nic_down_timeout: "5m"
    nic: "{{ mgmt_nic_name }}"
    random_hosts: random_one_mq_host
  tags:
    - mq-mgmt-nic-down
    - service
    - mq
    - mq-service
    - control


# Stress RabbitMQ Cluster
- include: rabbitmq/stress.yml
  tags:
    - service
    - mq
    - mq-service
    - control
    - mq-stress
