- name: Preparing for db node tests
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    shuffle_db_hosts: "{{ groups['db'] | shuffle }}"
    db_group_num: "{{ groups['db'] | length }}"
  tasks:
    - name: Random select one db host
      add_host:
        groups: random_one_db_host
        name: "{{ groups['db'] | random }}"
      when:
        - db_group_num | int >= 1

    - name: Random select two db hosts
      add_host:
        groups: random_two_db_hosts
        name: "{{ item }}"
      with_items:
        - "{{ shuffle_db_hosts[:2] }}"
      when:
        - db_group_num | int >= 2

    - name: Random select three db hosts
      add_host:
        groups: random_three_db_hosts
        name: "{{ item }}"
      with_items:
        - "{{ shuffle_db_hosts[:3] }}"
      when:
        - db_group_num | int >= 3
  tags:
    - db-pre


# Service down
- include: mysql/service.yml
  tags:
    - service
    - db
    - db-service
    - control


# We mainly test the impact to the MySQL cluster when
# there are network problems
- include: mysql/system.yml
  tags:
    - system
    - db
    - db-system
    - control

# Stress MySQL Cluster
- include: mysql/stress.yml
  tags:
    - service
    - db
    - db-service
    - control
    - db-stress
