- name: Preparing for api node tests
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    shuffle_api_hosts: "{{ groups['api'] | shuffle }}"
    api_group_num: "{{ groups['api'] | length }}"
  tasks:
    - name: Random select one api host
      add_host:
        groups: random_one_api_host
        name: "{{ groups['api'] | random }}"
      when:
        - api_group_num | int >= 1

    - name: Random select two api hosts
      add_host:
        groups: random_two_api_hosts
        name: "{{ item }}"
      with_items:
        - "{{ shuffle_api_hosts[:2] }}"
      when:
        - api_group_num | int >= 2

    - name: Random select three api hosts
      add_host:
        groups: random_three_api_hosts
        name: "{{ item }}"
      with_items:
        - "{{ shuffle_api_hosts[:3] }}"
      when:
        - api_group_num | int >= 3
  tags:
    - api-pre

## Service Level

# Nova
- include: nova/service.yml
  tags:
    - service
    - api
    - api-service
    - control
    - nova

# Cinder
- include: cinder/service.yml
  tags:
    - service
    - api
    - api-service
    - control
    - cinder

# Glance
- include: glance/service.yml
  tags:
    - service
    - api
    - api-service
    - control
    - glance

# Neutron
- include: neutron/service.yml
  tags:
    - service
    - api
    - api-service
    - control
    - neutron

# Keystone
- include: keystone/service.yml
  tags:
    - service
    - api
    - api-service
    - control
    - keystone
