# Stop and start memcache releated services on control node

- include: ../../common/service.yml
  vars:
    random_hosts: random_one_mc_host
    service_name: memcached

- include: ../../common/service.yml
  vars:
    random_hosts: random_two_mc_hosts
    service_name: memcached

- include: ../../common/service.yml
  vars:
    random_hosts: random_three_mc_hosts
    service_name: memcached
