- block:
   - name: Kill Ceph OSD daemon
     command: "pkill --pidfile /var/run/ceph/osd.{{ item }}.pid"
     args:
       removes: "/var/run/ceph/osd.{{ item }}.pid"
     become: true
     with_items:
       - "{{ osd_down_list }}"

   - name: Use Systemd to kill Ceph OSD daemon
     command: "systemctl kill ceph-osd@{{ item }}"
     args:
       creates: "/var/run/ceph/osd.{{ item }}.pid"
     become: true
     with_items:
       - "{{ osd_down_list }}"

  always:
   - name: Waiting 10 seconds to warm down
     pause:
       seconds: 10
