- block:
   - name: Kill ceph monitor daemon
     shell: pkill ceph-mon
     become: true
     ignore_errors: true

   - name: Check if ceph monitor was killed
     shell: "ps -ef | grep ceph-mon"
     register: ps_result
     become: true

   - fail:
       msg: "Failed to kill ceph monitor daemon"
     when: "'/usr/bin/ceph-mon' in ps_result.stdout"

  always:
   - name: Waiting 10 seconds to warm down
     pause:
       seconds: 10
