- block:
   - name: "Reset failed ceph osd status "
     shell: "systemctl reset-failed ceph-osd@{{ item }}"
     args:
       creates: "/etc/init.d/ceph"
     become: true
     with_items:
       - "{{ osd_down_list }}"

   - name: "Start Ceph OSD"
     shell: "systemctl start ceph-osd@{{ item }}"
     args:
       creates: "/etc/init.d/ceph"
     become: true
     with_items:
       - "{{ osd_down_list }}"

   - shell: "/etc/init.d/ceph start osd.{{ item }}"
     args:
       removes: "/etc/init.d/ceph"
     become: true
     with_items:
       - "{{ osd_down_list }}"

  always:
   - name: Waiting 10 seconds to warm up
     pause:
       seconds: 10
