- name: Create local working dir
  hosts: localhost
  roles:
    - provision/local
  tags:
    - provision

- name: Random select a storage host
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - set_fact:
        random_host: "{{ groups['storage'] | random }}"

- name: Create non root user on storage nodes
  hosts: "{{ random_host }}"
  roles:
    - provision/user
  tags:
    - provision

- name: Run fault drills on storage nodes in the system level
  hosts: "{{ random_host }}"
  roles:
    - storage/system

# Finally, we conditionally remove basic setup (users,
# groups, directories)to start from scratch
- name: Tear down non-root user on storage hosts
  hosts: "{{ random_host }}"
  roles:
    - provision/teardown
  tags:
    - teardown-provision
